name: tekartik_gdrive_api_utils
description: G drive api utils
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  cv: ">=1.1.3"
  googleapis: any
  http: any
  path: ">=1.9.0"
  tekartik_io_auth_utils:
    git:
      url: https://github.com/tekartik/io_auth_utils.dart
      ref: dart3a
  # path: ^1.8.0

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
